In [1]:
import pandas as pd

# File path of the Excel file
file_path = r"..\..\data\Raw_data\2014 Ele Deaths.xlsx"

# Rows to skip while reading the Excel file
rows_to_skip = [0, 32, 62, 96, 127, 158, 191, 223, 240, 241, 242, 243, 244, 245, 246]

# Read the Excel file into a pandas DataFrame
df = pd.read_excel(file_path, skiprows=rows_to_skip)

In [48]:
df

,No,Region,District,D.S. Divition,Death Of Date,Death Of Place,Death Of Course,Sex,Age
0,1,Eastern,Baticola,Chencalladi,14-01-2104,Kutampuri,Hakkapatas,Male,25-30
1,2,Eastern,Ampara,Ampara,28-01-2014,Himadurawa,Accident,Male,30-35
2,3,Eastern,Ampara,Uhana,28-01-2014,Himadurawa,Gunshot,Male,12-15
3,4,Eastern,Baticola,Kiran,31-01-2014,Aliyaode,Unknown,Male,5-7
4,5,Eastern,Ampara,Uhana,29-01-2014,Dambeala,Hakkapatas,Male,12-15
...,...,...,...,...,...,...,...,...,...
226,227,Southern,Rathnapura,Embilipitiya,July,ETH,Natural,Male,NaN
227,228,Southern,Rathnapura,Embilipitiya,July,ETH,Natural,Male,NaN
228,229,Southern,Rathnapura,Embilipitiya,september,ETH,Natural,Female,NaN
229,230,Southern,Rathnapura,Embilipitiya,september,ETH,Natural,Male,NaN
230,231,Southern,Rathnapura,Embilipitiya,October,ETH,Natural,Female,NaN

In [49]:
df.columns

Index([' No', 'Region', 'District', 'D.S. Divition', 'Death Of Date',
       'Death Of Place', 'Death Of Course', 'Sex', 'Age '],
      dtype='object')

In [50]:
def replace_column_names(column_name):
    translations = {
        ' No': 'No',
        'D.S. Divition': 'D/S Office',
        'Death Of Date': 'Date of Death',
        'Death Of Course': 'Cause of Death',
        'Death Of Place': 'Place of Death',
        'Age ':'Age'
    }
    return translations.get(column_name, column_name)

In [51]:
df.rename(columns=replace_column_names, inplace=True)

In [52]:
df.columns

Index(['No', 'Region', 'District', 'D/S Office', 'Date of Death',
       'Place of Death', 'Cause of Death', 'Sex', 'Age'],
      dtype='object')

In [53]:
df = df.drop(columns=['Place of Death'])

In [54]:
df['Region'].unique()

array(['Eastern', 'Wavniya', 'Kilinochchiya', 'Anuradhapura',
       'Polonnaruwa', 'Uva', 'Central', 'Northwestern', 'Southern'],
      dtype=object)

In [55]:
df['Region'] = df['Region'].replace({
        'Wawniya': 'Vavuniya',
        'Wavniya':'Vavuniya',
        'Kilinochchiya':'Kilinochchi',
        'Northwestern':'North Western'
})

In [56]:
df['Region'].unique()

array(['Eastern', 'Vavuniya', 'Kilinochchi', 'Anuradhapura',
       'Polonnaruwa', 'Uva', 'Central', 'North Western', 'Southern'],
      dtype=object)

In [57]:
df['District'].unique()

array(['Baticola', 'Ampara', 'Badulla', 'Mannar', 'Wavniya', 'Mulathiw',
       'Anuradhapura', 'Puttalama', 'Polonnaruwa', 'Trincomale',
       'Mathale', 'Hambanthota', 'Monaragala', 'Nuwaraeliya', 'Kandy',
       'Kurunagala', 'Rathnapura '], dtype=object)

In [58]:
df['District'] = df['District'].replace({
        'Mathale': 'Matale',
        'Wavniya':'Vavuniya',
        'Mulathiw':'Mullaitivu',
        'Baticola':'Batticaloa',
        'Puttalama':'Puttalam',
        'Trincomale':'Trincomalee',
        'Kurunagala':'Kurunegala',
        'Rathnapura ':'Ratnapura',
        'Hambanthota':'Hambantota',
        'Nuwaraeliya':'Nuwara Eliya'


})

In [59]:
df['District'].unique()

array(['Batticaloa', 'Ampara', 'Badulla', 'Mannar', 'Vavuniya',
       'Mullaitivu', 'Anuradhapura', 'Puttalam', 'Polonnaruwa',
       'Trincomalee', 'Matale', 'Hambantota', 'Monaragala',
       'Nuwara Eliya', 'Kandy', 'Kurunegala', 'Ratnapura'], dtype=object)

In [60]:
df['D/S Office'].unique()

array(['Chencalladi', 'Ampara', 'Uhana', 'Kiran', 'Lahugala',
       'Addalachchena', 'Mahiyanganaya', 'Samanthurai', 'Mahaoya',
       'Dehiattakandiya', 'Damana', 'Wavnathiw', 'Wakare', nan,
       'Welikanda', 'Walachchena Central', 'Pattipola', 'Eragama',
       'Nananttan', 'Manthei West', 'Musali', 'Wavniya north', 'Madu',
       'Thunukkai', 'Oddusudan', 'Pudukuduiruppu', 'Ma.Nu. Gampalatha',
       'Madwachchiya', 'Palugaswewa', 'Thirappane', 'Madawachchiya',
       'Nochchiyagama', 'Wanathavilluwa', 'Thalawa', 'Kakirawa',
       'Ma: Nu gampalatha', 'Horowpothana', 'Mahavilachchiya',
       'Kahatagasdigiliya', 'Madirigiriya', 'Lankapura', 'Elahara',
       'Hinguraggoda', 'Gomarankadawala', 'Thambalagamuwa', 'Kanthale',
       'Nagara ha Kadawath', 'Dimbulagala', 'Serunuwara', 'Morawewa',
       'Kinniya', 'Muthur', 'Vilgamuwa', 'Naula', 'Thamankaduwa',
       'Lunugamwehera', 'Bibila', 'Thissamaharamaya', 'siyabalanduwa',
       'Madulla', 'Kataragama', 'Buttala', 'Monaragala', 'Wallawaya',
       'Hanguranketha', 'Walapane', 'Haldummulla', 'Kandakatiya',
       'Ududumbara', 'Ahatuwawa', 'Galnawa', 'Karuwalagaswawa',
       'Nawagathegama', 'Palagala', 'Kotawehera', 'Galgamuwa',
       'Ambanpola', 'Thanamalvila', 'Hambanthota', 'Sooriyawawa',
       'Balangoda', 'Weligepola', 'Sevanagala', 'Embilipitiya'],
      dtype=object)

In [61]:
df[df['D/S Office'].isnull()]

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
35,36,Eastern,Ampara,NaN,2014-09-16,Unknown,NaN,NaN
63,64,Kilinochchi,Mullaitivu,NaN,08-2014,Gunshot,Male,1
166,167,Uva,Monaragala,NaN,09-09-2014,Gunshot,Female,30-35

In [62]:
df["D/S Office"]=df['D/S Office'].fillna("Unknown")

In [63]:
df['Date of Death'].unique()

array(['14-01-2104', '28-01-2014', '31-01-2014', '29-01-2014',
       '08-02-2014', '2014-02-10', '16-02-2014', '26-02-2014',
       '23-03-2014', '25-03-2014', '05-04-2014', '07-04-2014',
       '10-04-2014', '12-04-2014', '23-04-2014', '05-05-2014',
       '2014-05-05', '06-05-2014', '07-05-2014', '26-05-2014',
       '23-05-2014', '07-06-2014', '20-06-2014', '21-07-2014',
       '31-07-2014', '01-08-2014', '07-08-2014', '25-08-2014',
       '31-08-2014', '11-09-2014', '21-09-2014', '23-09-2014',
       '2014-09-16', '03-10-2014', '06-10-2014', '15-10-2014',
       '20-10-2014', '30-10-2014', '21-11-2014', '26-11-2014',
       '29-11-2014', '02-12-2014', '12-12-2014', '14-12-2014',
       '20-12-2014', '03-03-2014', '10-03-2014', '18-03-2014',
       '16-03-2014', '19-03-2014', '30-09-2014', '03-11-2014',
       '28-11-2014', nan, '03-05-2014', '31-05-2014', '08-2014',
       '19-01-2014', '23-01-2014', '24-01-2014', '02-02-2014',
       '07-02-2014', '05-03-2014', '09-03-2014', '11-03-2014',
       '26-03-2014', '02-04-2014', '24-05-2014', '05-07-2014',
       '10-07-2014', '23-08-2014', '30-08-2014', '09-09-2014',
       '15-09-2014', '22-09-2014', '20-09-2014', '07-10-2014',
       '13-10-2014', '28-10-2014', '06-12-2014', '09-01-2014',
       '12-01-2014', '16-01-2014', '27-01-2014', '05-02-2014',
       '11-02-2014', '14-02-2014', '18-02-2014', '21-02-2014',
       '04-02-2014', '22-02-2014', '28-02-2014', '01-03-2014',
       '12-03-2014', '27-03-2014', '30-03-2014', '17-04-2014',
       '26-04-2014', '02-05-2014', '09-05-2014', '11-05-2014',
       '01-06-2014', '02-06-2014', '18-07-2014', '30-07-2014',
       '12-08-2014', '18-08-2014', '19-08-2014', '20-08-2014',
       '22-08-2014', '28-09-2014', '01-10-2014', '19-11-2014',
       '15-12-2014', '31-12-2014', '30-01-2014', '08-03-2014',
       '08-05-2014', '20-05-2014', '25-05-2014', '04-06-2014',
       '25-07-2014', '  20-08-2014', '02-10-2014', '23-10-2014',
       '30-04-2014', '05-06-2014', '30-06-2014', '27-07-2014',
       '23-07-2014', '04-09-2014', '20-03-2014', '31-03-2014',
       '08-04-2014', '15-04-2014', '10-05-2014', '09-06-2014',
       '29-07-2014', '8-08-2014', '10-12-2014', '23-12-2014',
       '05-01-2014', '17-01-2014', '20-01-2014', '23-02-2014',
       '13-03-2014', '03-04-2014', '08-07-2014', '12-07-2014',
       '17-07-2014', '03-08-2014', '10-08-2014', '14-08-2014',
       '15-08-2014', '08-09-2014', '27-09-2014', '16-11-2014',
       '20-11-2014', '05-12-2014', 'January', 'March', 'May', 'July',
       'september', 'October'], dtype=object)

In [64]:
df['Date of Death'] = df['Date of Death'].replace({
    '14-01-2104':'14-01-2014',
    '08-2014': '31-08-2014',
    '  20-08-2014':'20-08-2014',
    'January':'31-01-2014',
    'March':'31-03-2014',
    'May':'31-05-2014',
    'July':'31-07-2014',
    'september':'30-09-2014',
    'October':'31-10-2014',
    '2014-05-05':'05-05-2014',
    '2014-09-16':'16-09-2014',
    '2014-02-10':'10-02-2014',
    '2014-12-31':'31-12-2014'



})

In [65]:
df[df['Date of Death'].isnull()]

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
59,60,Kilinochchi,Mullaitivu,Thunukkai,NaN,NaN,NaN,NaN
154,155,Uva,Monaragala,Bibila,NaN,Unknown,Male,45
155,156,Uva,Monaragala,Bibila,NaN,Unknown,Female,20
164,165,Uva,Monaragala,Madulla,NaN,Natural,Male,40-45

In [66]:
df['Date of Death'] = df['Date of Death'].fillna('31-12-2014')

In [67]:
df['Date of Death'].unique()

array(['14-01-2014', '28-01-2014', '31-01-2014', '29-01-2014',
       '08-02-2014', '10-02-2014', '16-02-2014', '26-02-2014',
       '23-03-2014', '25-03-2014', '05-04-2014', '07-04-2014',
       '10-04-2014', '12-04-2014', '23-04-2014', '05-05-2014',
       '06-05-2014', '07-05-2014', '26-05-2014', '23-05-2014',
       '07-06-2014', '20-06-2014', '21-07-2014', '31-07-2014',
       '01-08-2014', '07-08-2014', '25-08-2014', '31-08-2014',
       '11-09-2014', '21-09-2014', '23-09-2014', '16-09-2014',
       '03-10-2014', '06-10-2014', '15-10-2014', '20-10-2014',
       '30-10-2014', '21-11-2014', '26-11-2014', '29-11-2014',
       '02-12-2014', '12-12-2014', '14-12-2014', '20-12-2014',
       '03-03-2014', '10-03-2014', '18-03-2014', '16-03-2014',
       '19-03-2014', '30-09-2014', '03-11-2014', '28-11-2014',
       '31-12-2014', '03-05-2014', '31-05-2014', '19-01-2014',
       '23-01-2014', '24-01-2014', '02-02-2014', '07-02-2014',
       '05-03-2014', '09-03-2014', '11-03-2014', '26-03-2014',
       '02-04-2014', '24-05-2014', '05-07-2014', '10-07-2014',
       '23-08-2014', '30-08-2014', '09-09-2014', '15-09-2014',
       '22-09-2014', '20-09-2014', '07-10-2014', '13-10-2014',
       '28-10-2014', '06-12-2014', '09-01-2014', '12-01-2014',
       '16-01-2014', '27-01-2014', '05-02-2014', '11-02-2014',
       '14-02-2014', '18-02-2014', '21-02-2014', '04-02-2014',
       '22-02-2014', '28-02-2014', '01-03-2014', '12-03-2014',
       '27-03-2014', '30-03-2014', '17-04-2014', '26-04-2014',
       '02-05-2014', '09-05-2014', '11-05-2014', '01-06-2014',
       '02-06-2014', '18-07-2014', '30-07-2014', '12-08-2014',
       '18-08-2014', '19-08-2014', '20-08-2014', '22-08-2014',
       '28-09-2014', '01-10-2014', '19-11-2014', '15-12-2014',
       '30-01-2014', '08-03-2014', '08-05-2014', '20-05-2014',
       '25-05-2014', '04-06-2014', '25-07-2014', '02-10-2014',
       '23-10-2014', '30-04-2014', '05-06-2014', '30-06-2014',
       '27-07-2014', '23-07-2014', '04-09-2014', '20-03-2014',
       '31-03-2014', '08-04-2014', '15-04-2014', '10-05-2014',
       '09-06-2014', '29-07-2014', '8-08-2014', '10-12-2014',
       '23-12-2014', '05-01-2014', '17-01-2014', '20-01-2014',
       '23-02-2014', '13-03-2014', '03-04-2014', '08-07-2014',
       '12-07-2014', '17-07-2014', '03-08-2014', '10-08-2014',
       '14-08-2014', '15-08-2014', '08-09-2014', '27-09-2014',
       '16-11-2014', '20-11-2014', '05-12-2014', '31-10-2014'],
      dtype=object)

In [68]:
# Convert the date column to pandas datetime format
df['Date of Death'] = pd.to_datetime(df['Date of Death'],format='%d-%m-%Y')

In [69]:
df['Date of Death'].unique()

<DatetimeArray>
['2014-01-14 00:00:00', '2014-01-28 00:00:00', '2014-01-31 00:00:00',
 '2014-01-29 00:00:00', '2014-02-08 00:00:00', '2014-02-10 00:00:00',
 '2014-02-16 00:00:00', '2014-02-26 00:00:00', '2014-03-23 00:00:00',
 '2014-03-25 00:00:00',
 ...
 '2014-08-03 00:00:00', '2014-08-10 00:00:00', '2014-08-14 00:00:00',
 '2014-08-15 00:00:00', '2014-09-08 00:00:00', '2014-09-27 00:00:00',
 '2014-11-16 00:00:00', '2014-11-20 00:00:00', '2014-12-05 00:00:00',
 '2014-10-31 00:00:00']
Length: 156, dtype: datetime64[ns]

In [70]:
df = df.sort_values(by='Date of Death').reset_index(drop=True)

In [71]:
df

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
0,192,Southern,Monaragala,Thanamalvila,2014-01-05,Natural,Female,30
1,97,Polonnaruwa,Polonnaruwa,Madirigiriya,2014-01-09,Gunshot,Female,15-18
2,98,Polonnaruwa,Polonnaruwa,Lankapura,2014-01-12,Hakkapatas,Male,15-20
3,1,Eastern,Batticaloa,Chencalladi,2014-01-14,Hakkapatas,Male,25-30
4,99,Polonnaruwa,Polonnaruwa,Elahara,2014-01-16,Gunshot,Female,15
...,...,...,...,...,...,...,...,...
226,60,Kilinochchi,Mullaitivu,Thunukkai,2014-12-31,NaN,NaN,NaN
227,153,Polonnaruwa,Polonnaruwa,Hinguraggoda,2014-12-31,Natural,Female,20-25
228,156,Uva,Monaragala,Bibila,2014-12-31,Unknown,Female,20
229,165,Uva,Monaragala,Madulla,2014-12-31,Natural,Male,40-45
230,155,Uva,Monaragala,Bibila,2014-12-31,Unknown,Male,45

In [72]:
df['No'] = df.index + 1

In [73]:
df

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
0,1,Southern,Monaragala,Thanamalvila,2014-01-05,Natural,Female,30
1,2,Polonnaruwa,Polonnaruwa,Madirigiriya,2014-01-09,Gunshot,Female,15-18
2,3,Polonnaruwa,Polonnaruwa,Lankapura,2014-01-12,Hakkapatas,Male,15-20
3,4,Eastern,Batticaloa,Chencalladi,2014-01-14,Hakkapatas,Male,25-30
4,5,Polonnaruwa,Polonnaruwa,Elahara,2014-01-16,Gunshot,Female,15
...,...,...,...,...,...,...,...,...
226,227,Kilinochchi,Mullaitivu,Thunukkai,2014-12-31,NaN,NaN,NaN
227,228,Polonnaruwa,Polonnaruwa,Hinguraggoda,2014-12-31,Natural,Female,20-25
228,229,Uva,Monaragala,Bibila,2014-12-31,Unknown,Female,20
229,230,Uva,Monaragala,Madulla,2014-12-31,Natural,Male,40-45
230,231,Uva,Monaragala,Bibila,2014-12-31,Unknown,Male,45

In [74]:
df['Cause of Death'].unique()

array(['Natural', 'Gunshot', 'Hakkapatas', 'Electrocted', 'Unknown',
       'Accident', 'Train accident', 'Body destroied', 'Other',
       'Injured in leg', 'consuption of garbage', 'Poisand', 'Injured',
       'Norepoted', 'To born', 'Injured & Poisend', 'Septasimiya',
       'Drowning', nan], dtype=object)

In [75]:
def replace_sinhala_with_english(text):
    translations = {
    'Poisand':'Poisned',
    'Injured in leg':'Injured',
    'Septasimiya':'Septicemia',
    'Norepoted':'Unknown',
    'Unknoun':'Unknown',
    'Electrocted':'Electrocuted',
    'Injured & Poisend':'Poisned',
    'Drowning':'Drowned',
    'Body destroied':'Body destroyed',
    'To born':'At born',
    'consuption of garbage':'Garbage consumption',
    'Train accident':'Train Accident'
    }
    return translations.get(text, text)

In [76]:
df["Cause of Death"] = df["Cause of Death"].apply(replace_sinhala_with_english)

In [77]:
df['Cause of Death'] = df['Cause of Death'].fillna('Unknown')

In [78]:
df['Cause of Death'].unique()

array(['Natural', 'Gunshot', 'Hakkapatas', 'Electrocuted', 'Unknown',
       'Accident', 'Train Accident', 'Body destroyed', 'Other', 'Injured',
       'Garbage consumption', 'Poisned', 'At born', 'Septicemia',
       'Drowned'], dtype=object)

In [79]:
df

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
0,1,Southern,Monaragala,Thanamalvila,2014-01-05,Natural,Female,30
1,2,Polonnaruwa,Polonnaruwa,Madirigiriya,2014-01-09,Gunshot,Female,15-18
2,3,Polonnaruwa,Polonnaruwa,Lankapura,2014-01-12,Hakkapatas,Male,15-20
3,4,Eastern,Batticaloa,Chencalladi,2014-01-14,Hakkapatas,Male,25-30
4,5,Polonnaruwa,Polonnaruwa,Elahara,2014-01-16,Gunshot,Female,15
...,...,...,...,...,...,...,...,...
226,227,Kilinochchi,Mullaitivu,Thunukkai,2014-12-31,Unknown,NaN,NaN
227,228,Polonnaruwa,Polonnaruwa,Hinguraggoda,2014-12-31,Natural,Female,20-25
228,229,Uva,Monaragala,Bibila,2014-12-31,Unknown,Female,20
229,230,Uva,Monaragala,Madulla,2014-12-31,Natural,Male,40-45
230,231,Uva,Monaragala,Bibila,2014-12-31,Unknown,Male,45

In [80]:
df['Sex'].unique()

array(['Female', 'Male', nan, 'Unknown', 'Tusker'], dtype=object)

In [81]:
df['Sex'] = df['Sex'].fillna('Unknown')

In [82]:
df['Sex'] = df['Sex'].replace({
    
    'Tusker':'Male'
})

In [83]:
df['Sex'].unique()

array(['Female', 'Male', 'Unknown'], dtype=object)

In [84]:
df['Age'].unique()

array(['30', '15-18', '15-20', '25-30', '15', '35', '20', '25', '20-25',
       '12-15', '30-35', nan, '5-7', '45', '10-11', '8-10', '1', '20-30',
       '10', '9-10', '2,1/2', 40, '40-45', '10-15', '3,1/2', '3-4', '7-9',
       '4', '35-40', '45-48', '4-5', '32', '40', '45-50', '3.1/2', '9',
       '18-20', '2 month', '4-6', '7', '6-8', '10-12', '7,1/2', '-6-7',
       '50-55', '30-40', '4,1/2', '5', 'To born', '5 month', '14', '18',
       '8', '50', '6', 5, '4 month', '7 month', '23', '55-60', '2', '11',
       '17'], dtype=object)

In [85]:
from numpy import nan
df['Age'] = df['Age'].replace({
    '2,1/2':'2.5',
    '3,1/2':'3.5',
    '3.1/2':'3.5',
    '2 month':'2 Months',
    'To born':'1 Day',
    '4 month':'4 Months',
    '7 month':'7 Months',
    '5 month':'5 Months',
    '7,1/2':'7.5',
    '4,1/2':'4.5',
    '-6-7':'6-7'

})

In [86]:
df['Age'] = df['Age'].fillna('Unknown')

In [87]:
df['Age'].unique()

array(['30', '15-18', '15-20', '25-30', '15', '35', '20', '25', '20-25',
       '12-15', '30-35', 'Unknown', '5-7', '45', '10-11', '8-10', '1',
       '20-30', '10', '9-10', '2.5', 40, '40-45', '10-15', '3.5', '3-4',
       '7-9', '4', '35-40', '45-48', '4-5', '32', '40', '45-50', '9',
       '18-20', '2 Months', '4-6', '7', '6-8', '10-12', '7.5', '6-7',
       '50-55', '30-40', '4.5', '5', '1 Day', '5 Months', '14', '18', '8',
       '50', '6', 5, '4 Months', '7 Months', '23', '55-60', '2', '11',
       '17'], dtype=object)

In [88]:
import re
# Function to convert months and weeks to years
def convert_to_years(age_str):
    if isinstance(age_str, str):
        if re.match(r'^\d+(\.\d+)? Months?$', age_str):
            months = float(re.match(r'^\d+(\.\d+)?', age_str).group())
            return months / 12  # Approximate conversion to years
        elif re.match(r'^\d+ Weeks?$', age_str):
            weeks = int(re.match(r'^\d+', age_str).group())
            return weeks / 52  # Approximate conversion to years
        elif re.match(r'^\d+ Days?$', age_str):
            days = int(re.match(r'^\d+', age_str).group())
            return days / 365  # Approximate conversion to years
        elif '-' in age_str:
            age_range = age_str.split('-')
            try:
                return (float(age_range[0]) + float(age_range[1])) / 2  # Taking the average for range
            except ValueError:
                return None  # Invalid range
    try:
        return float(age_str)
    except ValueError:
        return None  # Unknown or invalid value

# Apply the conversion function to the 'Age' column
df['age'] = df['Age'].apply(convert_to_years)

# Function to categorize age
def categorize_age(age):
    if age is None or isinstance(age, str):
        return 'Unknown'
    elif age < 1:
        return 'Infant'
    elif age <= 4:
        return 'Calf'
    elif age <= 12:
        return 'Juvenile'
    elif age >=13:
        return 'Subadults and adults'
    else:
        return 'Unknown'

# Apply the function to the 'Age' column
df['Age Category'] = df['age'].apply(categorize_age)

# Drop the original 'Age' column if you don't need it anymore
df.drop(columns=['age'], inplace=True)

In [89]:
df.tail(50)

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age,Age Category
181,182,Polonnaruwa,Trincomalee,Muthur,2014-09-23,Gunshot,Male,30-35,Subadults and adults
182,183,Southern,Hambantota,Hambanthota,2014-09-27,Other,Female,35,Subadults and adults
183,184,Polonnaruwa,Polonnaruwa,Welikanda,2014-09-28,Unknown,Unknown,25-30,Subadults and adults
184,185,Polonnaruwa,Polonnaruwa,Welikanda,2014-09-28,Unknown,Unknown,7 Months,Infant
185,186,Anuradhapura,Anuradhapura,Kakirawa,2014-09-30,Gunshot,Male,45,Subadults and adults
186,187,Southern,Ratnapura,Embilipitiya,2014-09-30,Natural,Male,Unknown,Unknown
187,188,Polonnaruwa,Polonnaruwa,Dimbulagala,2014-09-30,Hakkapatas,Female,30,Subadults and adults
188,189,Vavuniya,Vavuniya,Wavniya north,2014-09-30,Electrocuted,Male,35,Subadults and adults
189,190,Southern,Ratnapura,Embilipitiya,2014-09-30,Natural,Female,Unknown,Unknown
190,191,Polonnaruwa,Polonnaruwa,Dimbulagala,2014-10-01,Hakkapatas,Male,35,Subadults and adults
191,192,Southern,Hambantota,Hambanthota,2014-10-02,Body destroyed,Unknown,6,Juvenile
192,193,Uva,Monaragala,Kataragama,2014-10-02,Poisned,Male,23,Subadults and adults
193,194,Eastern,Ampara,Dehiattakandiya,2014-10-03,Unknown,Unknown,10-15,Unknown
194,195,Eastern,Ampara,Uhana,2014-10-06,Hakkapatas,Male,3-4,Calf
195,196,Anuradhapura,Anuradhapura,Thalawa,2014-10-07,Accident,Male,20-25,Subadults and adults
196,197,Anuradhapura,Anuradhapura,Kakirawa,2014-10-13,Hakkapatas,Female,4,Calf
197,198,Eastern,Ampara,Damana,2014-10-15,Unknown,Female,10-15,Unknown
198,199,Southern,Ratnapura,Weligepola,2014-10-15,Unknown,Male,55-60,Subadults and adults
199,200,Anuradhapura,Anuradhapura,Mahavilachchiya,2014-10-20,Hakkapatas,Male,2,Calf
200,201,Anuradhapura,Anuradhapura,Mahavilachchiya,2014-10-20,Other,Male,2,Calf
201,202,Eastern,Batticaloa,Welikanda,2014-10-20,Hakkapatas,Male,15-20,Subadults and adults
202,203,Eastern,Batticaloa,Kiran,2014-10-20,Unknown,Female,11,Juvenile
203,204,Uva,Monaragala,Wallawaya,2014-10-23,Natural,Female,35,Subadults and adults
204,205,Anuradhapura,Anuradhapura,Kahatagasdigiliya,2014-10-28,Accident,Female,4 Months,Infant
205,206,Eastern,Batticaloa,Walachchena Central,2014-10-30,Injured,Female,15,Subadults and adults
206,207,Southern,Ratnapura,Embilipitiya,2014-10-31,Natural,Female,Unknown,Unknown
207,208,Vavuniya,Mannar,Musali,2014-11-03,Unknown,Male,8,Juvenile
208,209,Southern,Monaragala,Thanamalvila,2014-11-16,Gunshot,Female,18-20,Subadults and adults
209,210,Polonnaruwa,Polonnaruwa,Welikanda,2014-11-19,Electrocuted,Female,30,Subadults and adults
210,211,Southern,Monaragala,Thanamalvila,2014-11-20,Gunshot,Female,15-20,Subadults and adults
211,212,Eastern,Ampara,Uhana,2014-11-21,Gunshot,Male,30-35,Subadults and adults
212,213,Eastern,Batticaloa,Pattipola,2014-11-26,Unknown,Male,5,Juvenile
213,214,Vavuniya,Mannar,Madu,2014-11-28,Unknown,Unknown,17,Subadults and adults
214,215,Anuradhapura,Puttalam,Wanathavilluwa,2014-11-28,Unknown,Male,20-25,Subadults and adults
215,216,Eastern,Ampara,Uhana,2014-11-29,Electrocuted,Male,Unknown,Unknown
216,217,Eastern,Ampara,Eragama,2014-12-02,Gunshot,Male,8,Juvenile
217,218,Southern,Ratnapura,Weligepola,2014-12-05,Gunshot,Male,45-50,Subadults and adults
218,219,Anuradhapura,Anuradhapura,Horowpothana,2014-12-06,Hakkapatas,Male,5,Juvenile
219,220,North Western,Kurunegala,Ambanpola,2014-12-10,Train Accident,Male,3-4,Calf
220,221,Eastern,Ampara,Uhana,2014-12-12,Poisned,Male,40,Subadults and adults
221,222,Eastern,Ampara,Dehiattakandiya,2014-12-14,Gunshot,Male,15-20,Subadults and adults
222,223,Polonnaruwa,Matale,Vilgamuwa,2014-12-15,Body destroyed,Female,7,Juvenile
223,224,Anuradhapura,Anuradhapura,Horowpothana,2014-12-20,Hakkapatas,Male,10,Juvenile
224,225,Eastern,Ampara,Damana,2014-12-20,Poisned,Male,8-10,Juvenile
225,226,North Western,Kurunegala,Galgamuwa,2014-12-23,Other,Female,20-25,Subadults and adults
226,227,Kilinochchi,Mullaitivu,Thunukkai,2014-12-31,Unknown,Unknown,Unknown,Unknown
227,228,Polonnaruwa,Polonnaruwa,Hinguraggoda,2014-12-31,Natural,Female,20-25,Subadults and adults
228,229,Uva,Monaragala,Bibila,2014-12-31,Unknown,Female,20,Subadults and adults
229,230,Uva,Monaragala,Madulla,2014-12-31,Natural,Male,40-45,Subadults and adults
230,231,Uva,Monaragala,Bibila,2014-12-31,Unknown,Male,45,Subadults and adults

In [90]:
output_file_path = r'..\..\data\Cleaned_data\2014_clean.csv'

df.to_csv(output_file_path, index=False)