In [1]:
import pandas as pd

# File path of the Excel file
file_path = r"..\..\data\Raw_data\2017.xlsx"

# Read the Excel file into a pandas DataFrame
df = pd.read_excel(file_path,skiprows=1)

In [59]:
df.head()

,අනු අංකය,කලාපය,දිස්ත්‍රික්කය,ප්‍රා.ලේ.කො. හෝ පොලිස් වසම,මියගිය දිනය හෝ අසන්නතම දිනය,මියයෑමට හේතුව,ස්ත්‍රි/පුරුෂ භාවය,වයස අවු:,ප.ම.ප. කර ඇති බව,මියගිය ස්ථානය GPS ඛණ්ඩාංක,Unnamed: 10
0,1,පොලොන්නරුව,පොලොන්නරුව,දිඹුලාගල,2017-01-01,වෙඩිවැදීමෙන් සිදු වු තුවාල නිසා,පිරිමි,35-40,ඇත,E 241078 - N 282669 දම්මින්න,NaN
1,2,නැඟෙනහිර,මඩකලපුව,අඩ්ඩාලච්චේන,2017-01-04,පොලිතින් ආහාරයට ගැනීම,පිරිමි,30-35,ඇත,අෂ්රොප් නගර්,(රක්ෂිතයෙන් පිටත)
2,3,පොලොන්නරුව,පොලොන්නරුව,වැලිකන්ද,2017-01-05,සඳහන් කර නැත,පිරිමි,8-10,NaN,284 මුතුවැල්ල,NaN
3,4,ඌව,මොනරාගල,බිබිල,2017-01-09,වෙඩිවැදීමෙන්,පිරිමි,21,නැත,E002557970 N00222181,NaN
4,5,නැඟෙනහිර,අම්පාර,තිරුක්කෝවිල්,2017-01-10,හක්කපටස් කෑමෙන්,ගැහැණු,5-6,ඇත,කාංචනකුඩා කුඹුරු ප්‍රදේශය,(පිටත)

In [60]:
def replace_column_names_with_english(column_name):
    translations = {
        'අනු අංකය': 'No',
        'කලාපය': 'Region',
        'දිස්ත්‍රික්කය': 'District',
        'ප්‍රා.ලේ.කො. හෝ පොලිස් වසම': 'D/S Office',
        'මියගිය දිනය හෝ අසන්නතම දිනය': 'Date of Death',
        'මියයෑමට හේතුව': 'Cause of Death',
        'ස්ත්‍රි/පුරුෂ භාවය': 'Sex',
        'වයස අවු: ': 'Age',
        'ප.ම.ප. කර ඇති බව': 'Reported to Police',
        'මියගිය ස්ථානය  GPS ඛණ්ඩාංක': 'Place of Death'
    }
    return translations.get(column_name, column_name)

In [61]:
df.rename(columns=replace_column_names_with_english, inplace=True)

In [62]:
df = df.drop(columns=['Place of Death','Reported to Police','Unnamed: 10'])

In [63]:
df.head()

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
0,1,පොලොන්නරුව,පොලොන්නරුව,දිඹුලාගල,2017-01-01,වෙඩිවැදීමෙන් සිදු වු තුවාල නිසා,පිරිමි,35-40
1,2,නැඟෙනහිර,මඩකලපුව,අඩ්ඩාලච්චේන,2017-01-04,පොලිතින් ආහාරයට ගැනීම,පිරිමි,30-35
2,3,පොලොන්නරුව,පොලොන්නරුව,වැලිකන්ද,2017-01-05,සඳහන් කර නැත,පිරිමි,8-10
3,4,ඌව,මොනරාගල,බිබිල,2017-01-09,වෙඩිවැදීමෙන්,පිරිමි,21
4,5,නැඟෙනහිර,අම්පාර,තිරුක්කෝවිල්,2017-01-10,හක්කපටස් කෑමෙන්,ගැහැණු,5-6

In [64]:
df.columns

Index(['No', 'Region', 'District', 'D/S Office', 'Date of Death',
       'Cause of Death', 'Sex', 'Age'],
      dtype='object')

In [65]:
df["Region"].unique()

array(['පොලොන්නරුව', 'නැඟෙනහිර', 'ඌව', 'අනුරාධපුරය', 'වයඔ',
       'ඇත්අතුරු සෙවන', 'වවුනියාව', 'පුත්තලම', 'දකුණ',
       'ත්\u200dරිකුණාමලය', 'වයඹ', 'මධ්\u200dයම ', 'කිලිනොච්චිය',
       'අනුරාධපුර', 'ඌව ', 'අනුරාපුරය'], dtype=object)

In [66]:
def replace_sinhala_with_english(text):
    translations = {
        'පොලොන්නරුව': 'Polonnaruwa',
        'නැඟෙනහිර': 'Eastern',
        'ඌව': 'Uva',
        'අනුරාධපුරය': 'Anuradhapura',
        'වයඔ': 'Wayamba',
        'ඇත්අතුරු සෙවන': 'Elephant Transit Home',
        'වවුනියාව': 'Vavuniya',
        'පුත්තලම': 'Puttalam',
        'දකුණ': 'Southern',
        'ත්\u200dරිකුණාමලය': 'Trincomalee',
        'වයඹ': 'Wayamba',
        'මධ්\u200dයම ': 'Central',
        'මධ්‍යම': 'Central',
        'කිලිනොච්චිය': 'Kilinochchi',
        'අනුරාධපුර': 'Anuradhapura',
        'ඌව ': 'Uva',
        'අනුරාපුරය': 'Anuradhapura'
    }
    return translations.get(text, text)

In [67]:
df["Region"] = df["Region"].apply(replace_sinhala_with_english)

In [68]:
df["Region"].unique()

array(['Polonnaruwa', 'Eastern', 'Uva', 'Anuradhapura', 'Wayamba',
       'Elephant Transit Home', 'Vavuniya', 'Puttalam', 'Southern',
       'Trincomalee', 'Central', 'Kilinochchi'], dtype=object)

In [69]:
df["District"].unique()

array(['පොලොන්නරුව', 'මඩකලපුව', 'මොනරාගල', 'අම්පාර', 'අනුරාධපුරය',
       'කුරුණෑගල', ' -  ', 'හම්බන්තොට', 'වවුනියාව', 'මන්නාරම', 'පුත්තලම',
       'ත්\u200dරිකුණාමලය', 'බදුල්ල', 'මුලතිව්', 'මාතලේ', 'රත්නපුරය',
       'අනුරාධුරය', 'කිලිනොච්චිය'], dtype=object)

In [70]:
df[df['District']==' -  ']

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
14,15,Elephant Transit Home,-,-,2017-01-,ස්වභාවික,පිරිමි,-
15,16,Elephant Transit Home,-,-,2017-01-,ස්වභාවික,ගැහැණු,-
125,126,Elephant Transit Home,-,-,2017-06-,ස්වභාවික,පිරිමි,-
162,163,Elephant Transit Home,-,-,2017-08-,ස්වභාවික,ගැහැණු,-
182,183,Elephant Transit Home,-,-,2017-09-,ස්වභාවික,ගැහැණු,-
208,209,Elephant Transit Home,-,-,2017-10-,ස්වභාවික,පිරිමි,-
255,256,Elephant Transit Home,-,-,2017-12-,ස්වභාවික,ගැහැණු,-

In [71]:
def replace_sinhala_with_english(text):
    translations = {
        'පොලොන්නරුව': 'Polonnaruwa',
        'නැඟෙනහිර': 'Eastern',
        'ඌව': 'Uva',
        'අනුරාධපුරය': 'Anuradhapura',
        'වයඔ': 'Wayamba',
        'ඇත්අතුරු සෙවන': 'Elephant Transit Home',
        'වවුනියාව': 'Vavuniya',
        'පුත්තලම': 'Puttalam',
        'දකුණ': 'Southern',
        'ත්‍රිකුණාමලය': 'Trincomalee',
        'වයඹ': 'Wayamba',
        'මධ්‍යම ': 'Central',
        'කිලිනොච්චිය': 'Kilinochchi',
        'අනුරාධපුර': 'Anuradhapura',
        'ඌව ': 'Uva',
        'අනුරාපුරය': 'Anuradhapura',
        'මඩකලපුව': 'Batticaloa',
        'මොනරාගල': 'Monaragala',
        'අම්පාර': 'Ampara',
        'කුරුණෑගල': 'Kurunegala',
        ' -  ': 'Ratnapura',
        'හම්බන්තොට': 'Hambantota',
        'මන්නාරම': 'Mannar',
        'ත්\u200dරිකුණාමලය': 'Trincomalee',
        'බදුල්ල': 'Badulla',
        'මුලතිව්': 'Mullaitivu',
        'මාතලේ': 'Matale',
        'රත්නපුරය': 'Ratnapura',
        'අනුරාධුරය': 'Anuradhapura',
        'කිලිනොච්චිය': 'Kilinochchi'
    }
    return translations.get(text, text)

In [72]:
df["District"] = df["District"].apply(replace_sinhala_with_english)

In [73]:
df["District"].unique()

array(['Polonnaruwa', 'Batticaloa', 'Monaragala', 'Ampara',
       'Anuradhapura', 'Kurunegala', 'Ratnapura', 'Hambantota',
       'Vavuniya', 'Mannar', 'Puttalam', 'Trincomalee', 'Badulla',
       'Mullaitivu', 'Matale', 'Kilinochchi'], dtype=object)

In [74]:
df

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age
0,1,Polonnaruwa,Polonnaruwa,දිඹුලාගල,2017-01-01,වෙඩිවැදීමෙන් සිදු වු තුවාල නිසා,පිරිමි,35-40
1,2,Eastern,Batticaloa,අඩ්ඩාලච්චේන,2017-01-04,පොලිතින් ආහාරයට ගැනීම,පිරිමි,30-35
2,3,Polonnaruwa,Polonnaruwa,වැලිකන්ද,2017-01-05,සඳහන් කර නැත,පිරිමි,8-10
3,4,Uva,Monaragala,බිබිල,2017-01-09,වෙඩිවැදීමෙන්,පිරිමි,21
4,5,Eastern,Ampara,තිරුක්කෝවිල්,2017-01-10,හක්කපටස් කෑමෙන්,ගැහැණු,5-6
...,...,...,...,...,...,...,...,...
251,252,Anuradhapura,Anuradhapura,කැබිතිගොල්ලෑව,2017-12-28,සිරුර නරක් වී ඇත,ගැහැණු,20
252,253,Eastern,Ampara,අඩ්ඩාලච්චේන,2017-12-28,පොලිතින් ආහාරයට ගැනීම,පිරිමි,12-15
253,254,Trincomalee,Trincomalee,කන්තලේ,2017-12-29,විදුලිසැර වැදීමෙන්,-,25-30
254,255,Central,Badulla,මහියංගණය,2017-12-31,හක්කපටස්,පිරිමි,-
255,256,Elephant Transit Home,Ratnapura,-,2017-12-,ස්වභාවික,ගැහැණු,-

In [75]:
df['D/S Office'].unique()

array(['දිඹුලාගල', 'අඩ්ඩාලච්චේන', 'වැලිකන්ද', 'බිබිල', 'තිරුක්කෝවිල්',
       'වාකරේ', 'හොරොව්පොතාන', 'පළුගස්වැව', 'මහඔය', 'නොච්චියාගම',
       'පොතුවිල්', 'අලිඅඩිවෙම්බු', 'පොල්පිතිගම', ' -  ',
       'මන්මුරේ නිරිත(පට්ටිපොල)', 'මැදවච්චිය', 'තිස්සමහාරාමය',
       'කහටගස්දිගිලිය', 'නෙදුන්කර්නි', 'අඩම්පන්', 'වනාතවිල්ලුව',
       'වැල්ලවාය', 'හම්බන්තොට', 'කැබිතිගොල්ලෑව', 'කිරාන්', 'ගෝමරන්කඩවල',
       'පලුගස්වැව', 'තණමල්විල', 'චෙන්කල්අඩි', 'තලාව', 'දමන',
       'තිරික්කෝවිල්', 'තමන්කඩුව', 'නැදුන්කර්නි', 'අඹන්පොල', 'විලච්චිය',
       'සියඹලාණ්ඩුව', 'සම්මන්තුරේ', 'මහියංගණය', 'නවගත්තේගම', 'වැලිඔය',
       'තිරප්පනේ', 'පුත්තලම දකුණ', 'කන්තලේ', 'ගල්ගමුව', 'හල්දුම්මුල්ල',
       'කන්දකැටිය', 'වවුනියාව', 'මුතූර්', 'පුත්තලම', 'සේරුවිල', 'මඩුල්ල',
       'කැකිරාව', 'නාඋල', 'ම. නු. ප.', 'හිඟුරක්ගොඩ', 'විල්ගමුව', 'ලාහුගල',
       'කුච්චවේලි', 'මැදිරිගිරිය', 'මොරවැව', 'මඩු', 'මොනරාගල', 'දඹුල්ල',
       'කොටවෙහෙර', 'කරුවලගස්වැව', 'බලංගොඩ', 'දෙහිඅත්තකණ්ඩිය',
       'මහකුඹුක්කඩවල', 'සෙට්ටිකුලම', 'සිරිපුර', 'චෙංකලඩි', 'සමන්තුරේ',
       'පලාගල', 'ඇලහැර', 'කතරගම', 'සුරියවැව', 'ගිරිබාව', 'බුත්තල',
       'ඇඹිලිපිටිය', 'සේරුනුවර', 'මුසලි', 'ඇහැටුවැව', 'නගර හා කඩවත්',
       'මාන්කුලම', 'මහවිලච්චිය', 'මහව', 'තිරප්පනය', 'චෙංකල්ලඩි',
       'ගලෙන්බිදුණුවැව', 'රඹෑව', 'වැලිගෙපොල'], dtype=object)

In [76]:
def replace_sinhala_with_english(text):
    translations = {
        'දිඹුලාගල':'Dimbulagala',
        'අඩ්ඩාලච්චේන':'Addalachchena',
        'වැලිකන්ද':'Welikanda',
        'බිබිල':'Bibila',
        'තිරුක්කෝවිල්':'Thirikkovil',
        'වාකරේ':'Wakare',
        'හොරොව්පොතාන':'Horowpathana',
        'පළුගස්වැව':'Palugaswewa',
        'මහඔය':'Mahaoya',
        'නොච්චියාගම':'Nochchiyagama',
        'පොතුවිල්':'Pothuwil',
        'අලිඅඩිවෙම්බු':'Alayadivembu',
        'පොල්පිතිගම':'Polpithigama',
        ' -  ':'Unknown',
        'මන්මුරේ නිරිත(පට්ටිපොල)':'Pattipola',
        'මැදවච්චිය':'Madavachchiya',
        'තිස්සමහාරාමය':'Thissamaharamaya',
        'කහටගස්දිගිලිය':'Kahatagasdigiliya',
        'නෙදුන්කර්නි':'Nedunkanar',
        'අඩම්පන්':'Adampan',
        'වනාතවිල්ලුව':'Wanathawilluwa',
        'වැල්ලවාය':'Wellawaya',
        'හම්බන්තොට':'Hambantota',
        'කැබිතිගොල්ලෑව':'Kabithigollawa',
        'කිරාන්':'Kiran',
        'ගෝමරන්කඩවල':'Gomarankadawala',
        'පලුගස්වැව':'Palugaswewa',
        'තණමල්විල':'Thanamalwila',
        'චෙන්කල්අඩි':'Chenkaladi',
        'තලාව':'Thalawa',
        'දමන':'Damana',
        'තිරික්කෝවිල්': 'Thirikkovil',
        'තමන්කඩුව': 'Tamankaduwa',
        'නැදුන්කර්නි': 'Nadunkanari',
        'අඹන්පොල': 'Ambanpola',
        'විලච්චිය': 'Vilachchiya',
        'සියඹලාණ්ඩුව': 'Siyabalanduwa',
        'සම්මන්තුරේ': 'Samanthurai',
        'මහියංගණය': 'Mahiyangana',
        'නවගත්තේගම': 'Navagattegama',
        'වැලිඔය': 'Welioya',
        'තිරප්පනේ': 'Tirappane',
        'පුත්තලම දකුණ': 'Puttalam',
        'කන්තලේ': 'Kanthale',
        'ගල්ගමුව': 'Galgamuwa',
        'හල්දුම්මුල්ල': 'Haldhummulla',
        'කන්දකැටිය': 'Kandakatiya',
        'වවුනියාව': 'vavuniya',
        'මුතූර්': 'Mutur',
        'පුත්තලම': 'Puttalam',
        'සේරුවිල': 'Seruvila',
        'මඩුල්ල': 'Madulla',
        'කැකිරාව': 'Kakirawa',
        'නාඋල': 'Naula',
        'ම. නු. ප.': 'M.N.P',
        'හිඟුරක්ගොඩ': 'Hingurakgoda',
        'විල්ගමුව': 'Vilgamuwa',
        'ලාහුගල': 'Lahugala',
        'කුච්චවේලි': 'Kuchchaveli',
        'මැදිරිගිරිය': 'Madirigiriya',
        'මොරවැව': 'Morawewa',
        'මඩු': 'Madu',
        'මොනරාගල': 'Monaragala',
        'දඹුල්ල': 'Dambulla',
        'කොටවෙහෙර': 'Kotavehera',
        'කරුවලගස්වැව': 'Karuwalgaswewa',
        'බලංගොඩ': 'Balangoda',
        'දෙහිඅත්තකණ්ඩිය': 'Dehiaththakandiya',
        'මහකුඹුක්කඩවල': 'Mahakubukkadawala',
        'සෙට්ටිකුලම': 'Settikulama',
        'සිරිපුර': 'Siripura',
        'චෙංකලඩි': 'Chankaladi',
        'සමන්තුරේ': 'Samanthurai',
        'පලාගල': 'Palagala',
        'ඇලහැර': 'Alahara',
        'කතරගම': 'Kataragama',
        'සුරියවැව': 'Suriyawewa',
        'ගිරිබාව': 'Giribawa',
        'බුත්තල': 'Buttala',
        'ඇඹිලිපිටිය': 'Ambilipitiya',
        'සේරුනුවර': 'Serunuwara',
        'මුසලි': 'Musali',
        'ඇහැටුවැව': 'Ahatuwewa',
        'නගර හා කඩවත්': 'Nagara Ha Kadavatha',
        'මාන්කුලම': 'Mankulama',
        'මහවිලච්චිය': 'Mahawilachchiya',
        'මහව': 'Mahawa',
        'තිරප්පනය': 'Tirappane',
        'චෙංකල්ලඩි': 'Chenkaladi',
        'ගලෙන්බිදුණුවැව': 'Galenbindunuwewa',
        'රඹෑව': 'Rambawa',
        'වැලිගෙපොල': 'Weligepola'
    }
    return translations.get(text, text)

In [77]:
df["D/S Office"] = df["D/S Office"].apply(replace_sinhala_with_english)

In [78]:
df['D/S Office'].unique()

array(['Dimbulagala', 'Addalachchena', 'Welikanda', 'Bibila',
       'Thirikkovil', 'Wakare', 'Horowpathana', 'Palugaswewa', 'Mahaoya',
       'Nochchiyagama', 'Pothuwil', 'Alayadivembu', 'Polpithigama',
       'Unknown', 'Pattipola', 'Madavachchiya', 'Thissamaharamaya',
       'Kahatagasdigiliya', 'Nedunkanar', 'Adampan', 'Wanathawilluwa',
       'Wellawaya', 'Hambantota', 'Kabithigollawa', 'Kiran',
       'Gomarankadawala', 'Thanamalwila', 'Chenkaladi', 'Thalawa',
       'Damana', 'Tamankaduwa', 'Nadunkanari', 'Ambanpola', 'Vilachchiya',
       'Siyabalanduwa', 'Samanthurai', 'Mahiyangana', 'Navagattegama',
       'Welioya', 'Tirappane', 'Puttalam', 'Kanthale', 'Galgamuwa',
       'Haldhummulla', 'Kandakatiya', 'vavuniya', 'Mutur', 'Seruvila',
       'Madulla', 'Kakirawa', 'Naula', 'M.N.P', 'Hingurakgoda',
       'Vilgamuwa', 'Lahugala', 'Kuchchaveli', 'Madirigiriya', 'Morawewa',
       'Madu', 'Monaragala', 'Dambulla', 'Kotavehera', 'Karuwalgaswewa',
       'Balangoda', 'Dehiaththakandiya', 'Mahakubukkadawala',
       'Settikulama', 'Siripura', 'Chankaladi', 'Palagala', 'Alahara',
       'Kataragama', 'Suriyawewa', 'Giribawa', 'Buttala', 'Ambilipitiya',
       'Serunuwara', 'Musali', 'Ahatuwewa', 'Nagara Ha Kadavatha',
       'Mankulama', 'Mahawilachchiya', 'Mahawa', 'Galenbindunuwewa',
       'Rambawa', 'Weligepola'], dtype=object)

In [79]:
df['Cause of Death'].unique()

array(['වෙඩිවැදීමෙන් සිදු වු තුවාල නිසා', 'පොලිතින් ආහාරයට ගැනීම',
       'සඳහන් කර නැත', 'වෙඩිවැදීමෙන්', 'හක්කපටස් කෑමෙන්',
       'සිරුර නරක් වී ඇත', 'වෙඩිවැදීමෙන් ', 'වෙඩි වැදීමෙන්',
       'වෙඩිවැදීමෙන් ඇතිවු තුවාල', 'පරපෝෂිත අසාධනය', 'විදුලිසැර වැදීමෙන්',
       'ස්වභාවික', 'කන්දෙන් පහලට පෙරලිමෙන්', 'විෂ ඔඩුදිවීම නිසා',
       'සඳහන් කරනොමැත', 'දුම්රියේ ගැටීමෙන්', 'තුවාල වී සිටිමෙන්',
       'හඳුනාගත නොහැක', 'හිසට වෙඩි වැදී\u200dමෙන්', 'අක්මාව හිරවීමෙන්',
       'හක්කපටස්', 'සඳහන්කර නැත', 'විෂක් ආග්\u200dරාහනය වීමෙන්',
       'සඳහන් කර නොමැත', 'අතෙහි ඇතිවූ තුවාලයක්',
       'ශරීරයේ තුවාල නිසා නිව්මෝනියව ', 'හදුනාගත නොහැක',
       'පිටගැස්ම සෑදීම හේතුවෙන්', 'ඇතෙකු පහරදීමෙන්', 'ඇතින්නට යටවීම නිසා',
       'රියඅනතුරකින්', 'බැක්ටීරිය ආසාදනයක්', 'බස් රථයක ගැටීමෙන්',
       'මඩවලක එරීමෙන්', 'ලිඳකට වැටීමෙන්', 'විෂ ශරීරගතවීමෙන්',
       'බර වාහනයක ගැටීමෙන්',
       'තනිදළ ඇතාගේ දකුණු ඇල ප්\u200dරදේශයට පහර දීමෙන්',
       'වැසිකිලි වලකට වැටීම', 'නිශ්චිතව සඳහන් කළ නොහැක', 'සඳහන් කළ නොහැක',
       'ගැබ්බර ඇතින්නක් පැටවා ප්\u200dරසුත කිරීමේදී', 'වෙඩිවැදීමකින්',
       'සෙප්ටමීනියා', 'ළිඳ තුලට වැටීම  නිසා', 'ඇලට වැටී තෙරපීමෙන්',
       'නිගමනය කළ නොහැක', 'කඳුසහිත බෑවුමකින් පහලට වැටී ගසක සිරවීමෙන්',
       'විෂබීජයක් ඇතුළුවීමෙන්', 'වලකට වැටී මඩේ එරීම නිසා',
       'වෙඩි වැදීම හා ඇතින්නක් පහරදී', 'රෝගී වීමෙන්',
       'පාලුවගා ළිඳකට වැටීමෙන්', 'රෝගයකින්',
       'පරණ තුවාල ඔඩුදීවිම හේතුවෙන්', 'වස ශරීරිගත වීමෙන්', 'වෙඩිවැදීම',
       'වස ලබාදීමෙන්', 'හක්කටපටස්', 'වම්පස ඉදිරි පාදයේ ඇති තුවාලයක් නිසා',
       'වම්පාදයේ ඇති තුවාලයක් නිසා', ' වෙඩිවැදීමන් බව',
       'විදුලිසැරවැදීමෙන්', 'වතුර සහිත ළිඳකට වැටී සිරවීමෙන්',
       'යතුරුපැදියක ගැටීමෙන්', 'මළ දරු උපතක්',
       'සිරුර දින 5 කට පසු හමුවි ඇත', 'වගාළිඳකට වැටීමෙන්', 'මඩේ එරීමෙන්',
       'පරපෝෂිත අසාදනය දුර්වල වී ජලයේ ගිලීම', 'මුඛයට වෙඩිවැදීමෙන්',
       'වෙඩිවැදීමක්', 'විදුලිසැර වැදිමෙන්',
       'වම්පාදයට අලියකු පහරදීමෙන්  සුසුම්නාවට හානි සිදුවීම',
       'වෙඩිතැබීමෙන්', 'විදුලි සැරවැදීමෙන්', 'ඉදිරිපාදය තුවාලවීම',
       'පැරණි තුවාල ඔඩුදිවීම නිසා', 'පරණ වැසිවලකට වැටීමෙන්',
       'වෙඩි තැබීමෙන්',
       'උපත ලද විගස ඇතින්නට හෝ වෙනත් අලියෙකුට හිස පෑගීමෙන්',
       'අතහි පැවැති තුවාලයක් නිසා', 'වෙඩි පහරක් නිසා',
       'අලියා ඇල්ලීමට ගොස් නිර්වින්දනය කළ පසු', 'රෝගයක් ',
       'අක්මා පැතැල්ල ආසාධනයවීම'], dtype=object)

In [80]:
def replace_sinhala_with_english(text):
    translations = {
        'වෙඩිවැදීමෙන් සිදු වු තුවාල නිසා':'Gunshot',
        'පොලිතින් ආහාරයට ගැනීම':'Eaten polythene',
        'සඳහන් කර නැත':'Unknown',
        'වෙඩිවැදීමෙන්':'Gunshot',
        'හක්කපටස් කෑමෙන්':'Hakkapatas',
        'සිරුර නරක් වී ඇත':'Body destroyed',
        'වෙඩිවැදීමෙන් ':'Gunshot',
        'වෙඩි වැදීමෙන්':'Gunshot',
        'වෙඩිවැදීමෙන් ඇතිවු තුවාල':'Gunshot',
        'පරපෝෂිත අසාධනය':'Other',
        'විදුලිසැර වැදීමෙන්':'Electrocuted',
        'ස්වභාවික':'Natural',
        'කන්දෙන් පහලට පෙරලිමෙන්':'Falling of a mountain',
        'විෂ ඔඩුදිවීම නිසා':'Poisned',
        'සඳහන් කරනොමැත':'Unknown',
        'දුම්රියේ ගැටීමෙන්':'Train Accident',
        'තුවාල වී සිටිමෙන්':'Injured',
        'හඳුනාගත නොහැක':'Unknown',
        'හිසට වෙඩි වැදී\u200dමෙන්':'Gunshot',
        'අක්මාව හිරවීමෙන්':'Other',
        'හක්කපටස්':'Hakkapatas',
        'සඳහන්කර නැත':'Unknown',
        'විෂක් ආග්\u200dරාහනය වීමෙන්':'Poisned',
        'සඳහන් කර නොමැත':'Unknown',
        'අතෙහි ඇතිවූ තුවාලයක්':'Injured',
        'ශරීරයේ තුවාල නිසා නිව්මෝනියව ':'Injured',
        'හදුනාගත නොහැක':'Unknown',
        'පිටගැස්ම සෑදීම හේතුවෙන්':'Other',
        'ඇතෙකු පහරදීමෙන්':'Attack by an elephant',
        'ඇතින්නට යටවීම නිසා':'Attack by an elephant',
        'රියඅනතුරකින්':'Accident',
        'බැක්ටීරිය ආසාදනයක්':'Disease',
        'බස් රථයක ගැටීමෙන්':'Accident',
        'මඩවලක එරීමෙන්':'Other',
        'ලිඳකට වැටීමෙන්':'Fallen into well',
        'විෂ ශරීරගතවීමෙන්':'Poisned',
        'බර වාහනයක ගැටීමෙන්':'Accident',
        'තනිදළ ඇතාගේ දකුණු ඇල ප්\u200dරදේශයට පහර දීමෙන්':'Attack by an elephant',
        'වැසිකිලි වලකට වැටීම':'Fallen into well',
        'නිශ්චිතව සඳහන් කළ නොහැක':'Unknown',
        'සඳහන් කළ නොහැක':'Unknown',
        'ගැබ්බර ඇතින්නක් පැටවා ප්\u200dරසුත කිරීමේදී':'At born',
        'වෙඩිවැදීමකින්':'Gunshot',
        'සෙප්ටමීනියා':'Septicemia',
        'ළිඳ තුලට වැටීම  නිසා':'Fallen into well',
        'ඇලට වැටී තෙරපීමෙන්':'Drowned',
        'නිගමනය කළ නොහැක':'Unknown',
        'කඳුසහිත බෑවුමකින් පහලට වැටී ගසක සිරවීමෙන්':'Falling of a mountain',
        'විෂබීජයක් ඇතුළුවීමෙන්':'Poisned',
        'වලකට වැටී මඩේ එරීම නිසා':'Fallen into well',
        'වෙඩි වැදීම හා ඇතින්නක් පහරදී':'Gunshot',
        'රෝගී වීමෙන්':'Disease',
        'පාලුවගා ළිඳකට වැටීමෙන්':'Fallen into well',
        'රෝගයකින්':'Disease',
        'පරණ තුවාල ඔඩුදීවිම හේතුවෙන්':'Injured',
        'වස ශරීරිගත වීමෙන්':'Poisned',
        'වෙඩිවැදීම':'Gunshot',
        'වස ලබාදීමෙන්':'Poisned',
        'හක්කටපටස්':'Hakkapatas',
        'වම්පස ඉදිරි පාදයේ ඇති තුවාලයක් නිසා':'Injured',
        'වම්පාදයේ ඇති තුවාලයක් නිසා':'Injured',
        ' වෙඩිවැදීමන් බව':'Gunshot',
        'විදුලිසැරවැදීමෙන්':'Electrocuted',
        'වතුර සහිත ළිඳකට වැටී සිරවීමෙන්':'Fallen into well',
        'යතුරුපැදියක ගැටීමෙන්':'Accident',
        'මළ දරු උපතක්':'At born',
        'සිරුර දින 5 කට පසු හමුවි ඇත':'Unknown',
        'වගාළිඳකට වැටීමෙන්':'Fallen into well',
        'මඩේ එරීමෙන්':'Other',
        'පරපෝෂිත අසාදනය දුර්වල වී ජලයේ ගිලීම':'Drowned',
        'මුඛයට වෙඩිවැදීමෙන්':'Gunshot',
        'වෙඩිවැදීමක්':'Gunshot',
        'විදුලි සැරවැදීමෙන්':'Electrocuted',
        'වම්පාදයට අලියකු පහරදීමෙන්  සුසුම්නාවට හානි සිදුවීම':'Broken the Spinal',
        'වෙඩිතැබීමෙන්':'Gunshot',
        'විදුලිසැර වැදිමෙන්':'Electrocuted',
        'ඉදිරිපාදය තුවාලවීම':'Injured',
        'පැරණි තුවාල ඔඩුදිවීම නිසා':'Injured',
        'පරණ වැසිවලකට වැටීමෙන්':'Fallen into well',
        'වෙඩි තැබීමෙන්':'Gunshot',
        'උපත ලද විගස ඇතින්නට හෝ වෙනත් අලියෙකුට හිස පෑගීමෙන්':'Attack by an elephant',
        'අතහි පැවැති තුවාලයක් නිසා':'Injured',
        'වෙඩි පහරක් නිසා':'Gunshot',
        'අලියා ඇල්ලීමට ගොස් නිර්වින්දනය කළ පසු':'Other',
        'රෝගයක් ':'Disease',
        'අක්මා පැතැල්ල ආසාධනයවීම':'Disease'


    }
    return translations.get(text, text)

In [81]:
df["Cause of Death"] = df["Cause of Death"].apply(replace_sinhala_with_english)

In [82]:
df['Cause of Death'].unique()

array(['Gunshot', 'Eaten polythene', 'Unknown', 'Hakkapatas',
       'Body destroyed', 'Other', 'Electrocuted', 'Natural',
       'Falling of a mountain', 'Poisned', 'Train Accident', 'Injured',
       'Attack by an elephant', 'Accident', 'Disease', 'Fallen into well',
       'At born', 'Septicemia', 'Drowned', 'Broken the Spinal'],
      dtype=object)

In [83]:
df['Cause of Death'].value_counts()

Cause of Death
Gunshot                  53
Hakkapatas               53
Unknown                  44
Electrocuted             25
Injured                  10
Natural                  10
Fallen into well          9
Poisned                   7
Train Accident            7
Other                     6
Attack by an elephant     6
Disease                   5
Body destroyed            5
Eaten polythene           4
Accident                  4
Falling of a mountain     2
At born                   2
Drowned                   2
Septicemia                1
Broken the Spinal         1
Name: count, dtype: int64

In [84]:
df['Sex'].unique()

array(['පිරිමි', 'ගැහැණු', 'හඳුනාගත නොහැක', nan, 'ඇතා', ' -',
       'සඳහන් කළ නොහැක', 'නොදනී', '-', ' - ', 'පුරුෂ', 'පැටියා',
       'අලි පැටියා', 'පිරිමි ඇතා', 'පිරිමි පැටවා', 'තනිදළ ඇතා', ' -  '],
      dtype=object)

In [85]:
df['Sex'] = df['Sex'].replace({
    'පිරිමි': 'Male',
    'ගැහැණු': 'Female',
    'හඳුනාගත නොහැක': 'Unknown',
    'ඇතා': 'Male',
    '-': 'Unknown',
    'සඳහන් කළ නොහැක': 'Unknown',
    'නොදනී': 'Unknown',
    ' -': 'Unknown',
    ' - ': 'Unknown',
    'පුරුෂ': 'Male',
    'පැටියා': 'Calf',
    'අලි පැටියා': 'Calf',
    'පිරිමි ඇතා': 'Male',
    'පිරිමි පැටවා': 'Male',
    'තනිදළ ඇතා': 'Male',
    ' -  ': 'Unknown'
})

In [86]:
df['Sex'] = df['Sex'].fillna('Unknown')

In [87]:
df['Sex'].unique()

array(['Male', 'Female', 'Unknown', 'Calf'], dtype=object)

In [88]:
df['Age'].unique()

array(['35-40', '30-35', '8-10', '21', '5-6', '20-25', '22-25', '4', '35',
       '15-18', '10-12', ' -  ', '20', '25', '25-35', '18-20', '30 - 35',
       '7 - 8', '16-18', '10-15', '29-30', '25-30', '20-22', '20-30',
       '30', nan, '12-17', '13', 15, 'දින 7', '28 - 30', 5, '25 - 30', 10,
       40, 35, 'මාස 01', '20 - 25', '35 - 40', 7, '8 - 10', '15 - 20',
       '3 - 4', 1, 30, 'සතියයි', '40 - 45', 25, '08 - 10', 6, '15-20',
       '14 - 20', 'මාස 5-8', 20, '16 - 18', '18 - 22', 50, '17 - 18',
       '2 - 2 1/2', '5 - 15', 'මාස 1', 8, '06 - 07', '50-55', '6-7',
       '35 - 40 ', '2-3', '12 - 15', 4.5, 'මා: 6-8', ' - ', '5-7', '15',
       'මාස 6-8', '55', '45', '1', '50 - 60', '5', 'මාස 3', '2 1/2',
       12.15, 3, ' අවු: 20 මාස 6', '4-5', 12, '10 - 12', '60', '1 1/2',
       '3,1/2', '12', 'මාස 04', '06', 'අවු: 24', '40', '30-40', '12-14',
       'නොදනී', '40-50', 18, '12-15', '31-35', '40-45', 17, 'පැටව්', 4,
       '24-25', '2,1/2', 2], dtype=object)

In [89]:
from numpy import nan
df['Age'] = df['Age'].replace({
   '30 - 35':'30-35',
   ' -  ':'Unknown',
   'මාස 01':'1 Month',
   'දින 7':'7 Days',
   '35 - 40':'35-40',
   'සතියයි':'1 Week',
   '15 - 20':'15-20',
   '08 - 10':'8-10',
   'මාස 5-8':'6.5 Weeks',
   'මාස 1':'1 Month',
   '06 - 07':'6-7',
   '12 - 15':'12-15',
   'මා: 6-8':'7 Months',
   ' - ':'Unknown',
   'මාස 6-8':'7 Months',
   'මාස 3':'3 Months',
   '2 1/2':'2.5',
   '12.15':'12-15',
   ' අවු: 20 මාස 6':'20.5',
   '10 - 12':'10-12',
   '1 1/2':'1.5',
   '3,1/2':'3.5',
   'මාස 04':'4 Months',
   '06':'6',
   'අවු: 24':'24',
   'නොදනී':'Unknown',
   'පැටව්':'Unknown',
   '2,1/2':'2.5',
   '5 - 15':'5-15',
   '2 - 2 1/2':'2-2.5',
   '16 - 18':'16-18',
   '25 - 30':'25-30',
   '3 - 4':'3-4',
   '50 - 60':'50-60',
   'nan':'Unknown',
   '7 - 8':'7-8'


})

In [90]:
df['Age'] = df['Age'].fillna('unknown')

In [91]:
df['Age'].unique()

array(['35-40', '30-35', '8-10', '21', '5-6', '20-25', '22-25', '4', '35',
       '15-18', '10-12', 'Unknown', '20', '25', '25-35', '18-20', '7-8',
       '16-18', '10-15', '29-30', '25-30', '20-22', '20-30', '30',
       'unknown', '12-17', '13', 15, '7 Days', '28 - 30', 5, 10, 40, 35,
       '1 Month', '20 - 25', 7, '8 - 10', '15-20', '3-4', 1, 30, '1 Week',
       '40 - 45', 25, 6, '14 - 20', '6.5 Weeks', 20, '18 - 22', 50,
       '17 - 18', '2-2.5', '5-15', 8, '6-7', '50-55', '35 - 40 ', '2-3',
       '12-15', 4.5, '7 Months', '5-7', '15', '55', '45', '1', '50-60',
       '5', '3 Months', '2.5', 12.15, 3, '20.5', '4-5', 12, '60', '1.5',
       '3.5', '12', '4 Months', '6', '24', '40', '30-40', '12-14',
       '40-50', 18, '31-35', '40-45', 17, 4, '24-25', 2], dtype=object)

In [92]:
import re
# Function to convert months and weeks to years
def convert_to_years(age_str):
    if isinstance(age_str, str):
        if re.match(r'^\d+(\.\d+)? Months?$', age_str):
            months = float(re.match(r'^\d+(\.\d+)?', age_str).group())
            return months / 12  # Approximate conversion to years
        elif re.match(r'^\d+ Weeks?$', age_str):
            weeks = int(re.match(r'^\d+', age_str).group())
            return weeks / 52  # Approximate conversion to years
        elif re.match(r'^\d+ Days?$', age_str):
            days = int(re.match(r'^\d+', age_str).group())
            return days / 365  # Approximate conversion to years
        elif '-' in age_str:
            age_range = age_str.split('-')
            try:
                return (float(age_range[0]) + float(age_range[1])) / 2  # Taking the average for range
            except ValueError:
                return None  # Invalid range
    try:
        return float(age_str)
    except ValueError:
        return None  # Unknown or invalid value

# Apply the conversion function to the 'Age' column
df['age'] = df['Age'].apply(convert_to_years)

# Function to categorize age
def categorize_age(age):
    if age is None or isinstance(age, str):
        return 'Unknown'
    elif age < 1:
        return 'Infant'
    elif age <= 4:
        return 'Calf'
    elif age <= 12:
        return 'Juvenile'
    elif age >=13:
        return 'Subadults and adults'
    else:
        return 'Unknown'

# Apply the function to the 'Age' column
df['Age Category'] = df['age'].apply(categorize_age)

# Drop the original 'Age' column if you don't need it anymore
df.drop(columns=['age'], inplace=True)

In [93]:
df

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age,Age Category
0,1,Polonnaruwa,Polonnaruwa,Dimbulagala,2017-01-01,Gunshot,Male,35-40,Subadults and adults
1,2,Eastern,Batticaloa,Addalachchena,2017-01-04,Eaten polythene,Male,30-35,Subadults and adults
2,3,Polonnaruwa,Polonnaruwa,Welikanda,2017-01-05,Unknown,Male,8-10,Juvenile
3,4,Uva,Monaragala,Bibila,2017-01-09,Gunshot,Male,21,Subadults and adults
4,5,Eastern,Ampara,Thirikkovil,2017-01-10,Hakkapatas,Female,5-6,Juvenile
...,...,...,...,...,...,...,...,...,...
251,252,Anuradhapura,Anuradhapura,Kabithigollawa,2017-12-28,Body destroyed,Female,20,Subadults and adults
252,253,Eastern,Ampara,Addalachchena,2017-12-28,Eaten polythene,Male,12-15,Subadults and adults
253,254,Trincomalee,Trincomalee,Kanthale,2017-12-29,Electrocuted,Unknown,25-30,Subadults and adults
254,255,Central,Badulla,Mahiyangana,2017-12-31,Hakkapatas,Male,Unknown,Unknown
255,256,Elephant Transit Home,Ratnapura,Unknown,2017-12-,Natural,Female,Unknown,Unknown

In [94]:
#pip install googletrans==4.0.0-rc1
'''
import pandas as pd
from googletrans import Translator

# Assuming you have a pandas DataFrame named 'df' and 'location' is the column with Sinhala location names
translator = Translator()

def translate_to_english(text):
    try:
        return translator.translate(text, src='si', dest='en').text
    except:
        return text

df['Death Location GPS Coordinates'] = df['Death Location GPS Coordinates'].apply(translate_to_english)
'''

"\nimport pandas as pd\nfrom googletrans import Translator\n\n# Assuming you have a pandas DataFrame named 'df' and 'location' is the column with Sinhala location names\ntranslator = Translator()\n\ndef translate_to_english(text):\n    try:\n        return translator.translate(text, src='si', dest='en').text\n    except:\n        return text\n\ndf['Death Location GPS Coordinates'] = df['Death Location GPS Coordinates'].apply(translate_to_english)\n"

In [95]:
df['Date of Death'].unique()

array(['2017-01-01', '2017-01-04', '2017-01-05', '2017-01-09',
       '2017-01-10', '2017-01-11', '2017-01-12', '2017-01-15',
       '2017-01-22', '2017-01-28', '2017-01-29', '2017-01-30',
       '2017-01-31', '2017-01-', '2017-02-01', '2017-02-02', '2017-02-05',
       '2017-02-06', '2017-02-07', '2017.02.10', '2017.02.11',
       '2017-02-11', '2017-02-12', '2017-02-14', '2017-02-17',
       '2017-02-19', '2017-02-20', '2017-02-22', '2017-02-24',
       '2017-02-27', '2017-02-28', '2017-03-02', '2017-03-03',
       '2017-03-04', '2017-03-06', '2017-03-10', '2017-03-11',
       '2017-03-19', '2017.03.20', '2017-03-20', '2017-03-21',
       '2017.03.22', '2017-03-29', '2017-04-01', '2017.04.01',
       '2017-04-03', '2017.04.04', '2017.04.08', '2017-04-09',
       '2017-04-10', '2017.04.12', '2017-04-14', '2017.04.15',
       '2017.04.17', '2017.04.18', '2017.04.20', '2017.04.22',
       '2017.04.24', '2017.04.25', '2017.04.27', '2017.04.26',
       '2017.04.28', '2017-04-28', '2017.05.01', '2017.05.02',
       '2017.05.05', '2017.05.07', '2017.05.11', '2017.05.12',
       '2017-05-14', '2017.05.15', '2017.05.16', '2017.05.17',
       '2017.05.20', '2017.05.23', '2017.05.24', '2017.05.25',
       '2017.05.26', '2017.05.28', '2017.05.29', '2017.06.01',
       '2017.06.09', '2017.06.10', '2017-06-11', '2017-06-12',
       '2017.06.13', '2017-06-14', '2017.06.18', '2017-06-15',
       '2017-06-25', '2017-06-20', '2017.06.25', '2017-06-23',
       '2017.06.28', '2017-06-', '2017.07.02', 'සදහන්කරනැත', '2017.07.10',
       '2017-07-12', '2017.07.13', '2017-07-15', '2017.07.16',
       '2017-07-20', '2017.07.23', '2017-07-25', '2017-07-28',
       '2017.08.02', '2017-08-02', '2017.08.04', '2017-08-05',
       '2017-08-06', '2017-08-07', '2017.08.11', '2017.08.15',
       '2017.08.16', '2017-08-16', '2017.08.17', '2017.08.18',
       '2017-08-23', '2017.08.23', '2017-08-25', '2017-08-28',
       '2017-08-30', '2017-08-', '2017.09.01', '2017-09-03', '2017-09-04',
       '2017.09.04', '2017-09-05', '2017.09.06', '2017-09-07',
       '2017-09-08', '2017-09-11', '2017-09-12', '2017-09-16',
       '2017-09-17', '2017-09-20', '2017-09-24', '2017-09-28',
       '2017.09.30', '2017-09-30', '2017-09-', 'නොදනි', '2017-10-01',
       '2017-10-02', '2017.10.03', '2017-10-04', '2017-10-05',
       '2017-10-10', '2017.10.10', '2017-10-13', '2017-10-14',
       '2017-10-15', '2017-10-19', '2017-10-21', '2017-10-24',
       '2017-10-25', '2017-10-27', '2017-10-29', '2017-10-30', '2017-10-',
       '2017-11-01', '2017-11-02', '2017-11-03', '2017-11-10',
       '2017-11-11', '2017-11-13', '2017-11-15', '2017-11-18',
       '2017-11-16', '2017-11-19', '2017-11-23', '2017-11-27',
       '2017-11-29', '2017-12-01', '2017-12-02', '2017-12-08',
       '2017-12-09', '2017-12-11', '2012-12-12', '2017-12-14',
       '2017-12-15', '2017-12-16', '2017-12-19', '2017-12-20',
       '2017-12-23', '2017-12-24', '2017-12-25', '2017-12-27', '2017-12-',
       '2017-12-28', '2017-12-29', '2017-12-31'], dtype=object)

In [96]:
df['Date of Death'] = df['Date of Death'].replace({
    '2017-01-': '2017-01-31',
    '2017-06-':'2017-06-28',
    '2017-08-':'2017-08-30',
    '2017-09-':'2017-09-30',
    '2017-10-':'2017-10-30',
    '2017-12-':'2017-12-28',
    'සදහන්කරනැත':'2017-01-01',
    'නොදනි':'2017-01-01',
    '2012-12-12':'2017-12-12'


})

In [97]:
df['Date of Death'].unique()

array(['2017-01-01', '2017-01-04', '2017-01-05', '2017-01-09',
       '2017-01-10', '2017-01-11', '2017-01-12', '2017-01-15',
       '2017-01-22', '2017-01-28', '2017-01-29', '2017-01-30',
       '2017-01-31', '2017-02-01', '2017-02-02', '2017-02-05',
       '2017-02-06', '2017-02-07', '2017.02.10', '2017.02.11',
       '2017-02-11', '2017-02-12', '2017-02-14', '2017-02-17',
       '2017-02-19', '2017-02-20', '2017-02-22', '2017-02-24',
       '2017-02-27', '2017-02-28', '2017-03-02', '2017-03-03',
       '2017-03-04', '2017-03-06', '2017-03-10', '2017-03-11',
       '2017-03-19', '2017.03.20', '2017-03-20', '2017-03-21',
       '2017.03.22', '2017-03-29', '2017-04-01', '2017.04.01',
       '2017-04-03', '2017.04.04', '2017.04.08', '2017-04-09',
       '2017-04-10', '2017.04.12', '2017-04-14', '2017.04.15',
       '2017.04.17', '2017.04.18', '2017.04.20', '2017.04.22',
       '2017.04.24', '2017.04.25', '2017.04.27', '2017.04.26',
       '2017.04.28', '2017-04-28', '2017.05.01', '2017.05.02',
       '2017.05.05', '2017.05.07', '2017.05.11', '2017.05.12',
       '2017-05-14', '2017.05.15', '2017.05.16', '2017.05.17',
       '2017.05.20', '2017.05.23', '2017.05.24', '2017.05.25',
       '2017.05.26', '2017.05.28', '2017.05.29', '2017.06.01',
       '2017.06.09', '2017.06.10', '2017-06-11', '2017-06-12',
       '2017.06.13', '2017-06-14', '2017.06.18', '2017-06-15',
       '2017-06-25', '2017-06-20', '2017.06.25', '2017-06-23',
       '2017.06.28', '2017-06-28', '2017.07.02', '2017.07.10',
       '2017-07-12', '2017.07.13', '2017-07-15', '2017.07.16',
       '2017-07-20', '2017.07.23', '2017-07-25', '2017-07-28',
       '2017.08.02', '2017-08-02', '2017.08.04', '2017-08-05',
       '2017-08-06', '2017-08-07', '2017.08.11', '2017.08.15',
       '2017.08.16', '2017-08-16', '2017.08.17', '2017.08.18',
       '2017-08-23', '2017.08.23', '2017-08-25', '2017-08-28',
       '2017-08-30', '2017.09.01', '2017-09-03', '2017-09-04',
       '2017.09.04', '2017-09-05', '2017.09.06', '2017-09-07',
       '2017-09-08', '2017-09-11', '2017-09-12', '2017-09-16',
       '2017-09-17', '2017-09-20', '2017-09-24', '2017-09-28',
       '2017.09.30', '2017-09-30', '2017-10-01', '2017-10-02',
       '2017.10.03', '2017-10-04', '2017-10-05', '2017-10-10',
       '2017.10.10', '2017-10-13', '2017-10-14', '2017-10-15',
       '2017-10-19', '2017-10-21', '2017-10-24', '2017-10-25',
       '2017-10-27', '2017-10-29', '2017-10-30', '2017-11-01',
       '2017-11-02', '2017-11-03', '2017-11-10', '2017-11-11',
       '2017-11-13', '2017-11-15', '2017-11-18', '2017-11-16',
       '2017-11-19', '2017-11-23', '2017-11-27', '2017-11-29',
       '2017-12-01', '2017-12-02', '2017-12-08', '2017-12-09',
       '2017-12-11', '2017-12-12', '2017-12-14', '2017-12-15',
       '2017-12-16', '2017-12-19', '2017-12-20', '2017-12-23',
       '2017-12-24', '2017-12-25', '2017-12-27', '2017-12-28',
       '2017-12-29', '2017-12-31'], dtype=object)

In [98]:
# Replace periods with hyphens in the 'Date of Death' column
df['Date of Death'] = df['Date of Death'].str.replace('.', '-')

# Convert the date column to pandas datetime format
df['Date of Death'] = pd.to_datetime(df['Date of Death'], format='%Y-%m-%d')

In [99]:
df['Date of Death'].unique()

<DatetimeArray>
['2017-01-01 00:00:00', '2017-01-04 00:00:00', '2017-01-05 00:00:00',
 '2017-01-09 00:00:00', '2017-01-10 00:00:00', '2017-01-11 00:00:00',
 '2017-01-12 00:00:00', '2017-01-15 00:00:00', '2017-01-22 00:00:00',
 '2017-01-28 00:00:00',
 ...
 '2017-12-16 00:00:00', '2017-12-19 00:00:00', '2017-12-20 00:00:00',
 '2017-12-23 00:00:00', '2017-12-24 00:00:00', '2017-12-25 00:00:00',
 '2017-12-27 00:00:00', '2017-12-28 00:00:00', '2017-12-29 00:00:00',
 '2017-12-31 00:00:00']
Length: 174, dtype: datetime64[ns]

In [100]:
df = df.sort_values(by='Date of Death').reset_index(drop=True)

In [101]:
df['No'] = df.index + 1

In [102]:
df.head(10)

,No,Region,District,D/S Office,Date of Death,Cause of Death,Sex,Age,Age Category
0,1,Polonnaruwa,Polonnaruwa,Dimbulagala,2017-01-01,Gunshot,Male,35-40,Subadults and adults
1,2,Uva,Monaragala,Kataragama,2017-01-01,Unknown,Male,30-35,Subadults and adults
2,3,Uva,Monaragala,Madulla,2017-01-01,Unknown,Unknown,Unknown,Unknown
3,4,Uva,Monaragala,Madulla,2017-01-01,Unknown,Unknown,7 Months,Infant
4,5,Uva,Ampara,Damana,2017-01-01,Unknown,Unknown,7 Months,Infant
5,6,Eastern,Batticaloa,Addalachchena,2017-01-04,Eaten polythene,Male,30-35,Subadults and adults
6,7,Polonnaruwa,Polonnaruwa,Welikanda,2017-01-05,Unknown,Male,8-10,Juvenile
7,8,Uva,Monaragala,Bibila,2017-01-09,Gunshot,Male,21,Subadults and adults
8,9,Eastern,Ampara,Thirikkovil,2017-01-10,Hakkapatas,Female,5-6,Juvenile
9,10,Eastern,Ampara,Thirikkovil,2017-01-11,Body destroyed,Female,20-25,Subadults and adults

In [103]:
output_file_path = r'..\..\data\Cleaned_data\2017_clean.csv'

df.to_csv(output_file_path, index=False)